### ISSUE TITLE
应该有个使用说明

### ISSUE THREAD

**Issue by cliuxinxin** [easychen/aiapi#1]
虽然我自己摸索出来了。

**Comment by easychen** [comment]
刚写完，没空搞。稍后我会和书籍自动生成工具一起录个视频教程。

**Comment by SA-GIMA** [comment]
Will the author's tutorial be posted on the details page or on Weibo?

**Comment by easychen** [comment]
![image](https://github.com/easychen/aiapi/assets/1294760/3e6c540f-6509-4420-a1c8-c4da19cae2cf)
https://github.com/easychen/aiapi/blob/master/README-CN.md#%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E
