### ISSUE TITLE
很好的工具 关键是如何使用？？？

### ISSUE THREAD

**Issue by shawokou123** [easychen/aiapi#3]
很好的工具 关键是如何使用？？？

**Comment by geekbb** [comment]
坐等教程

**Comment by easychen** [comment]
![image](https://github.com/easychen/aiapi/assets/1294760/f6709907-5152-452a-b63f-0919b2126f7d)


https://github.com/easychen/aiapi/blob/master/README-CN.md#%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E

**Comment by shawokou123** [comment]
我按照你 的设置，但是这个key不起作用:

python3.10 make_book.py --book_name fanyi1.txt --model claude --claude_key http://127.0.0.1:3456 --language ja --single_translate

**Comment by shawokou123** [comment]
你好，有些问题。这个key，是什么呢？

比如，api地址是127.0.0.1：3456
用了您这个工具后，api key，改如何填写呢

**Comment by easychen** [comment]
> 你好，有些问题。这个key，是什么呢？
> 
> 比如，api地址是127.0.0.1：3456 用了您这个工具后，api key，改如何填写呢

不检测key，你可以用 sk1234567890

**Comment by shawokou123** [comment]
> > 你好，有些问题。这个key，是什么呢？
> > 比如，api地址是127.0.0.1：3456 用了您这个工具后，api key，改如何填写呢
> 
> 不检测key，你可以用 sk1234567890

你好，感谢回复。这个 sk1234567890，是需要填写在CookieCloud password，框中么？

**Comment by shawokou123** [comment]
我觉得你应该出一个更加详细的说明，目前这个根本用不成

**Comment by easychen** [comment]
https://www.bilibili.com/video/BV1Ku4y1q75F?t=946.6

**Comment by shawokou123** [comment]
好的，谢谢！
