### ISSUE TITLE
请问这个api能用在沉浸式翻译里的openai api吗，谢谢

### ISSUE THREAD

**Issue by nuyangneo** [easychen/aiapi#4]
rt

**Comment by easychen** [comment]
![image](https://github.com/easychen/aiapi/assets/1294760/fc17aec0-3d7e-4824-858e-67608333be55)

测试了下，虽然请求可以跑通，但有两个问题

1. 沉浸式翻译的瞬间并发太高，claude官网并不是为api设计的，因为不支持高并发，会报错
2.沉浸式翻译的提示词是为OpenAI API优化的，而 claude官网是一个对话模型，并不是特别擅长翻译。

**Comment by nuyangneo** [comment]
谢谢
