### ISSUE TITLE
claude-2 cookie失效了，再重新获取填写？

### ISSUE THREAD

**Issue by sosojustdo** [easychen/aiapi#5]
claude-2 cookie失效了，再重新获取填写？

**Comment by easychen** [comment]
两个解决办法：

1. 重新复制粘贴
2. 通过CookieCloud插件直接推送（ 插件推送时，AiAPI需要启动着 ）

教程说明 https://www.bilibili.com/video/BV1Ku4y1q75F?t=946.6
